In [12]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [35]:
df = pd.read_csv('scores.csv')
df

    id  s1  s2  s3  s4  s5  s6  s7  s8  s9
0    1   3   5   1   4   4   1   1   3   4
1    2   2   3   3   4   5   2   1   2   5
2    3   4   3   3   4   4   2   1   3   4
3    4   2   4   3   2   4   2   2   2   3
4    5   2   5   1   5   4   1   2   3   4
5    6   3   5   1   3   4   2   3   3   4
6    7   2   3   1   3   4   2   2   3   4
7    8   4   5   1   5   5   2   2   3   5
8    9   2   5   2   2   4   1   2   2   5
9   10   2   5   1   5   4   2   2   3   5
10  11   3   4   3   5   4   2   2   3   4
11  12   2   5   3   5   3   1   2   4   5
12  13   4   3   3   5   4   1   3   2   4
13  14   3   5   3   4   4   1   2   3   4
14  15   2   5   2   2   4   1   2   3   2
15  16   4   5   3   5   4   1   3   4   2
16  17   2   5   2   5   4   1   2   3   3
17  18   2   5   3   5   4   1   2   3   4
18  19   2   3   2   5   3   3   3   3   2
19  20   3   5   3   5   4   1   3   3   2
20  21   2   5   3   5   5   2   3   3   4
21  22   4   3   4   5   5   3   2   4   4
22  23   2   5   2   4   4   2   1   4   1
23  24   2   2   3   4   4   2   2   3   4
24  25   2   5   3   4   3   2   2   3   5

In [21]:
def comfort_label(score):
    if score >= 4:
        return 1  # 1 - комфортно
    else:
        return 0  # 0 - некомфортно

In [22]:
for col in df.columns[1:]:
    df[f'{col}_comfortable'] = df[col].apply(comfort_label)

In [28]:
df

,id,s1,s2,s3,s4,s5,s6,s7,s8,s9,s1_comfortable,s2_comfortable,s3_comfortable,s4_comfortable,s5_comfortable,s6_comfortable,s7_comfortable,s8_comfortable,s9_comfortable
0,1,3,5,1,4,4,1,1,3,4,0,1,0,1,1,0,0,0,1
1,2,2,3,3,4,5,2,1,2,5,0,0,0,1,1,0,0,0,1
2,3,4,3,3,4,4,2,1,3,4,1,0,0,1,1,0,0,0,1
3,4,2,4,3,2,4,2,2,2,3,0,1,0,0,1,0,0,0,0
4,5,2,5,1,5,4,1,2,3,4,0,1,0,1,1,0,0,0,1
5,6,3,5,1,3,4,2,3,3,4,0,1,0,0,1,0,0,0,1
6,7,2,3,1,3,4,2,2,3,4,0,0,0,0,1,0,0,0,1
7,8,4,5,1,5,5,2,2,3,5,1,1,0,1,1,0,0,0,1
8,9,2,5,2,2,4,1,2,2,5,0,1,0,0,1,0,0,0,1
9,10,2,5,1,5,4,2,2,3,5,0,1,0,1,1,0,0,0,1
10,11,3,4,3,5,4,2,2,3,4,0,1,0,1,1,0,0,0,1
11,12,2,5,3,5,3,1,2,4,5,0,1,0,1,0,0,0,1,1
12,13,4,3,3,5,4,1,3,2,4,1,0,0,1,1,0,0,0,1
13,14,3,5,3,4,4,1,2,3,4,0,1,0,1,1,0,0,0,1
14,15,2,5,2,2,4,1,2,3,2,0,1,0,0,1,0,0,0,0
15,16,4,5,3,5,4,1,3,4,2,1,1,0,1,1,0,0,1,0
16,17,2,5,2,5,4,1,2,3,3,0,1,0,1,1,0,0,0,0
17,18,2,5,3,5,4,1,2,3,4,0,1,0,1,1,0,0,0,1
18,19,2,3,2,5,3,3,3,3,2,0,0,0,1,0,0,0,0,0
19,20,3,5,3,5,4,1,3,3,2,0,1,0,1,1,0,0,0,0
20,21,2,5,3,5,5,2,3,3,4,0,1,0,1,1,0,0,0,1
21,22,4,3,4,5,5,3,2,4,4,1,0,1,1,1,0,0,1,1
22,23,2,5,2,4,4,2,1,4,1,0,1,0,1,1,0,0,1,0
23,24,2,2,3,4,4,2,2,3,4,0,0,0,1,1,0,0,0,1
24,25,2,5,3,4,3,2,2,3,5,0,1,0,1,0,0,0,0,1

In [29]:
df_long = pd.melt(df, id_vars=['id'],
                  value_vars=[f's{i}_comfortable' for i in range(1, 10)],
                  var_name='element', value_name='comfortable')

In [30]:
X = df_long[['element']]
X = pd.get_dummies(X, columns=['element'], drop_first=True)
y = df_long['comfortable']

In [31]:
X = sm.add_constant(X)

In [ ]:
logit_model = sm.Logit(y, X.astype(float))
result = logit_model.fit()

In [ ]:
print(result.summary())